// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "viewerTable-viewerenv",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:d24cfc52-f85e-4b86-820b-ec2cb89342f4",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_I1KOpx9QZ",
    "aws_user_pools_web_client_id": "12hdj97t3djbgnk3o1okn018sh",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "viewerApi",
            "endpoint": "https://64li5t44jg.execute-api.ap-southeast-1.amazonaws.com/viewerenv",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
